combine_control_expr = false

wrap_comments = true
comment_width = 70

control_brace_style = "AlwaysSameLine"

fn_args_layout = "Tall"
fn_single_line = false

force_explicit_abi = false
force_multiline_blocks = false

format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true

tab_spaces = 4
hard_tabs = true

imports_indent = "Visual"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"

indent_style = "Block"

match_block_trailing_comma = true
trailing_comma = "Never"
trailing_semicolon = true

max_width = 120
newline_style = "Unix"

normalize_comments = false

overflow_delimited_expr = true

remove_nested_parens = true

reorder_impl_items = true
reorder_imports = false

group_imports = "StdExternalCrate"

space_after_colon = true
space_before_colon = false
spaces_around_ranges = false

struct_lit_single_line = false

type_punctuation_density = "Wide"

use_field_init_shorthand = true
use_try_shorthand = true
